apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::129285410470:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-A39OVIL1G9IU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::129285410470:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-29T16:29:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1772"
  uid: 7be3aedd-1c16-4b87-b127-1bc2195c3c40
